// import moment from 'moment'
import pretty from 'pretty'
import cheerio from 'cheerio'

// function getType (val) {
//   return ({}).toString.call(val).match(/\s([a-zA-Z]+)/)[1].toLowerCase()
// }

/**
 * Given html, read and parse
 * @param  {string} html html file contents
 * @return {object}      Object containing a contents and data key
 */
function webpageify (html) {
  const $ = cheerio.load(html)
  let payload = {}
  const script = $('script').text()
  if (script != null && script) {
    payload.data = JSON.parse(script).frontmatter
  } else {
    payload.data = {}
  }

  const body = $('body').html()
  if (body != null && body) {
    payload.content = body
  } else {
    payload.content = ''
  }
  return payload
}

webpageify.stringify = function (html, data, options) {
  if (typeof html !== 'string') {
    throw Error('Stringify needs to recieve a string.')
  }
  let header = '<meta charset="UTF-8"><!-- This HTML file was generated by Collate. http://collatenotes.com. HTML generated is for preview purposes only. Collate uses the data in the frontmatter json to generate the body contents in the application. -->'
  for (let key in data) {
    switch (key) {
      case 'title':
        header += '<title>' + data[key] + '</title>'
        break
    }
  }
  header += '<script type="application/json">' + JSON.stringify({frontmatter: data}) + '</script>'

  const style = `<style>
  body {
    margin: 40px auto;
    max-width: 650px;
    font-size: 18px;
    padding: 0 10px;
  }
  p {
    margin: .5em 0;
  }
  img {
    max-width: 650px;
  }
  blockquote {
    border-left: 4px solid #ccc;
  }
  h1,h2,h3 {
    line-height: 1.2em;
  }
  .ql-font-monospace {
    font-family: Monospace;
  }
  .ql-font-serif {
    font-family: Serif;
  }
  </style>`
  return pretty('<!DOCTYPE html><html>' + '<head>' + header + style + '</head>' + '<body>' + html + '</body>' + '</html>')
}

export default webpageify
