// Default settings used by electron-settings
export default {
  update: '',
  collectionPath: [],
  disableAutosave: false,
  spellcheck: false,
  notebookPaneSortBy: 'Mod',
  notebookPaneSortDir: 'Asc',
  tagPaneSortBy: 'Num',
  tagPaneSortDir: 'Desc',
  notePaneSortBy: 'Modified',
  notePaneSortDir: 'Asc',
  notePaneListType: 'card',
  editorNewNoteType: 'markdown',
  editorNewNoteTypeButtonText: 'Markdown',
  loadStrategy: 'async',
  walkthrough: true,
  keyboardShortcuts: {
    quitProgram: 'ctrl-q',
    saveNote: 'ctrl-s',
    newNote: 'ctrl-n',
    newNotebook: 'ctrl-alt-n',
    newWindow: 'ctrl-shift-n',
    findOnPage: 'ctrl-f',
    searchNotes: 'ctrl-shift-f',
    collectionPane: 'ctrl-alt-/',
    notebookPaneUp: 'ctrl-shift-up',
    notebookPaneDown: 'ctrl-shift-down',
    notePaneUp: 'ctrl-up',
    notePaneDown: 'ctrl-down',
    notePaneFirst: 'ctrl-pgup',
    notePaneLast: 'ctrl-pgdown',
    settings: 'ctrl-,',
    showHelpPane: '',
    editorBold: 'ctrl-b',
    editorItalic: 'ctrl-i',
    editorUnderline: 'ctrl-u',
    editorHeadingBigger: 'ctrl-h',
    editorHeadingSmaller: '',
    editorCodeBlock: 'ctrl-alt-c',
    editorCleanBlock: '',
    editorBlockQuote: 'ctrl-`',
    editorUnorderedList: 'ctrl-l',
    editorOrderedList: '',
    editorInsertImage: 'ctrl-alt-k',
    editorInsertLink: 'ctrl-k',
    editorPreview: 'ctrl-p',
    editorSideBySide: 'f9',
    editorFullScreen: ''
  },
  defaultNotebookId: {},
  defaultCollectionId: '',
  markdownEditor: {
    previewEnabled: false
  },
  richtextEditor: {
    font: 'sans-serif'
  },
  autoHideMenuBar: false
}
